echo '{"chave": 0}' > out/nome0.json
echo '{"chave": 1}' > out/nome1.json
echo '{"chave": 2}' > out/nome2.json
echo '{"chave": 3}' > out/nome3.json
echo '{"chave": 4}' > out/nome4.json
echo '{"chave": 5}' > out/nome5.json
echo '{"chave": 6}' > out/nome6.json
echo '{"chave": 7}' > out/nome7.json
echo '{"chave": 8}' > out/nome8.json
echo '{"chave": 9}' > out/nome9.json
