name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Server
      run: docker build ./server

  build-downloader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Downloader
      run: docker build ./downloader

  build-uploader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Uploader
      run: docker build ./uploader
